export const images = {
  heroPortrait: {
    src: "/images/IMG_7045.webp",
    alt: "Jade Massentoff - dramatic portrait with red background and gold chains",
    width: 1080,
    height: 1080,
  },
  darkAngel: {
    src: "/images/DSC00055_2200.webp",
    alt: "Jade Massentoff - dark angel wings editorial shoot",
    width: 2200,
    height: 1939,
  },
  neonCouch: {
    src: "/images/resized-image.webp",
    alt: "Jade Massentoff - neon purple studio shoot",
    width: 1000,
    height: 1500,
  },
  neonStudio: {
    src: "/images/resized-image (1).webp",
    alt: "Jade Massentoff - neon magenta studio portrait",
    width: 1000,
    height: 1500,
  },
  neonClose: {
    src: "/images/resized-image (3).webp",
    alt: "Jade Massentoff - intimate neon purple closeup",
    width: 1000,
    height: 1500,
  },
  moodyBW: {
    src: "/images/bodysuit11992_2200.webp",
    alt: "Jade Massentoff - moody artistic portrait",
    width: 2200,
    height: 1168,
  },
  artBW: {
    src: "/images/bodysuit12014_2200.webp",
    alt: "Jade Massentoff - artistic portrait with beaded frame",
    width: 1650,
    height: 2200,
  },
  bwLounge: {
    src: "/images/resized-image (4).webp",
    alt: "Jade Massentoff - black and white lounge portrait",
    width: 1000,
    height: 1500,
  },
  yellowCar: {
    src: "/images/resized-image (5).webp",
    alt: "Jade Massentoff - yellow wig car photoshoot",
    width: 1000,
    height: 1500,
  },
  urbanEdgy: {
    src: "/images/surika-2_2200.webp",
    alt: "Jade Massentoff - urban graffiti street style",
    width: 1412,
    height: 2200,
  },
  goldArches: {
    src: "/images/resized-image (2).webp",
    alt: "Jade Massentoff - elegant gold architecture portrait",
    width: 1400,
    height: 1119,
  },
  speakerYellow: {
    src: "/images/D95FCAB5-A0C2-453B-AEA8-D992AE6FE91A_Original.webp",
    alt: "Jade Massentoff - yellow wig on speaker",
    width: 1080,
    height: 1350,
  },
  yellowGraffiti: {
    src: "/images/2745B0AF-5C9A-4880-8B8B-DA90ED551F2F_Original.webp",
    alt: "Jade Massentoff - yellow wig graffiti wall",
    width: 1080,
    height: 1080,
  },
};
